# Generated by Django 5.2.7 on 2025-10-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_productsize_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
