# Generated by Django 5.2.7 on 2025-10-30 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
