# Generated by Django 5.2.7 on 2025-10-31 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='sentiment_score',
            field=models.FloatField(default=0.0),
        ),
    ]
